trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"  # Group Name
- name: snyk_token  # Create a Token in Synk Portal
  value: $[variables.SNYKTOKEN]


# Creating Environmental Variable by using Export Linux Command because snyk accepts only Capital Letters and it's 
# as own environmental variable

# -fn just for our demonstrates purpose build won't fail by using -fn but in real time no need to mention

#Most teams don’t want this behavior for security scans. Instead, you’d typically:

#Use -ff (fail-fast) or no failure flag at all, to let Maven fail the build if Snyk finds a vulnerability.

# Adding SYNK Plugin to Maven.

<plugin>
  <groupId>io.snyk</groupId>
  <artifactId>snyk-maven-plugin</artifactId>
  <version>2.1.0</version>
  <executions>
    <execution>
      <id>snyk-test</id>
      <phase>test</phase>
      <goals><goal>test</goal></goals>
    </execution>
    <execution>
      <id>snyk-monitor</id>
      <phase>install</phase>
      <goals><goal>monitor</goal></goals>
    </execution>
  </executions>
  <configuration>
    <apiToken>${env.SNYK_API_TOKEN}</apiToken>
    <failOnIssues>false</failOnIssues>
  </configuration>
</plugin>


steps:
- script: |
    SNYK_TOKEN=$(snyk_token)
    export SNYK_TOKEN   
    mvn snyk:test -fn 
  displayName: "Integrate SCA scan using Snyk in ADO DevSecOps Pipeline"
