trigger:
- master

pool:
  vmImage: ubuntu-latest 
 #  name: Sonarqube (name of the pool) 



# Search for the SonarCloud template and select build task for which Language we need to prepare the analysis

#Preparation Sonar Analysis Configuration
steps:
- task: SonarCloudPrepare
  inputs: 
          Sonarqube: "SonarCloud"  # Mention Service Connection Name
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'Project_Name'  #Project Name
          cliSources: '.'

- task: SonarCloud Analyze
  inputs: 
          jdkversion: 'JAVA_HOME_17_X64' # For Java Based Applications

- task: SonarCloud Publish Quality Gates
  displayName: Publish Quality Gates Result    
  inputs:
          pollingTimeoutSec: '300'
          enabled: false

#(OR)
 #trigger:
#- master

#pool:
  #vmImage: ubuntu-latest

jobs:
- job: Sonar_SAST_Scan_Job
  container: maven:3.8.1-openjdk-17-slim
  steps:
  - script: |
      mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=<Our_OrganisationKey> -Dsonar.projectKey=<Our_Project_Key> -Dsonar.token=<Our_Token>
    displayName: "Integrate SAST using SonarCloud to populate code coverage and secure pipeline variable in Azure DevOps DevSecOps Pipeline"


